"""
API Gateway — Fraud Alert ORM Model
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    String,
    Boolean,
    ForeignKey,
    JSON,
    DateTime,
    Enum as SAEnum,
    ARRAY,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, UUIDMixin, TimestampMixin


class FraudAlert(Base, UUIDMixin, TimestampMixin):
    """Fraud alert generated by the anomaly detection engine."""

    __tablename__ = "fraud_alerts"

    transaction_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("transactions.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    risk_level: Mapped[str] = mapped_column(
        SAEnum("low", "medium", "high", "critical", name="risk_level"),
        nullable=False,
    )
    violated_rules: Mapped[list[str]] = mapped_column(
        ARRAY(String), nullable=False
    )
    details: Mapped[dict] = mapped_column(
        JSON, default=dict, server_default="{}"
    )
    is_resolved: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false"
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    transaction: Mapped["Transaction"] = relationship(
        "Transaction", back_populates="fraud_alert"
    )
    user: Mapped["User"] = relationship("User", back_populates="fraud_alerts")

    def __repr__(self) -> str:
        return (
            f"<FraudAlert(id={self.id}, user_id={self.user_id}, "
            f"risk={self.risk_level}, rules={self.violated_rules})>"
        )
